{
  "props": {
    "singleton": true
  },
  "components": {
    "httpClient": {
      "type": "bundle\\http\\HttpClient",
      "x": 176,
      "y": 272,
      "props": {
        "requestType": "URLENCODE",
        "responseType": "JSON",
        "connectTimeout": "15000",
        "readTimeout": "0",
        "followRedirects": "1",
        "proxyType": "DIRECT",
        "userAgent": "GameClient"
      }
    },
    "database": {
      "type": "bundle\\sql\\SqliteClient",
      "x": 320,
      "y": 224,
      "props": {
        "file": "user_settings.db",
        "autoOpen": true,
        "catchErrors": "1",
        "transactionIsolation": 8
      }
    },
    "player": {
      "type": "script\\MediaPlayerScript",
      "x": 240,
      "y": 192,
      "props": {
        "autoplay": "1",
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    }
  }
}